[tool.black]
line-length = 100
preview = true

[tool.isort]
atomic = true
profile = "black"
skip = [".venv"]

[tool.poetry]
name = "pipeline-lib"
version = "0.1.0"
description = "A library for designing and re-using ML pipelines"
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [{ include = "pipeline_lib" }]

[tool.poetry.dependencies]
python = "^3.9"
pandas = "^2.2.1"
pyarrow = "^15.0.0"
PyYAML = "^6.0.1"
scikit-learn = ">=1.4.0"
optuna = "^3.5.0"
optuna-dashboard = "^0.15.0"
explainerdashboard = "^0.4.5"
xgboost = { version = "^2.0.3", optional = true }
category-encoders = "^2.6.3"
tqdm = "^4.66.2"
pvlib = "^0.10.4"

[tool.poetry.extras]
xgboost = ["xgboost"]
all_models = ["xgboost"]

[tool.poetry.group.dev.dependencies]
flake8 = "^7.0.0"
black = "^23.12.1"
isort = "^5.13.2"
ipykernel = "^6.29.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
